# Generated by Django 4.0.1 on 2022-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='image_url',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='img_url',
            field=models.CharField(default='https://i.pinimg.com/564x/af/a4/cc/afa4cc7ccfca3de5986521730366ee91.jpg', max_length=500),
        ),
    ]
